/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyRating {
        "maxValue": number;
        "value": number;
    }
    interface MyRatingStar {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyRatingElement extends Components.MyRating, HTMLStencilElement {
    }
    var HTMLMyRatingElement: {
        prototype: HTMLMyRatingElement;
        new (): HTMLMyRatingElement;
    };
    interface HTMLMyRatingStarElement extends Components.MyRatingStar, HTMLStencilElement {
    }
    var HTMLMyRatingStarElement: {
        prototype: HTMLMyRatingStarElement;
        new (): HTMLMyRatingStarElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-rating": HTMLMyRatingElement;
        "my-rating-star": HTMLMyRatingStarElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyRating {
        "maxValue"?: number;
        "onRatingUpdated"?: (event: CustomEvent<any>) => void;
        "value"?: number;
    }
    interface MyRatingStar {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-rating": MyRating;
        "my-rating-star": MyRatingStar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-rating": LocalJSX.MyRating & JSXBase.HTMLAttributes<HTMLMyRatingElement>;
            "my-rating-star": LocalJSX.MyRatingStar & JSXBase.HTMLAttributes<HTMLMyRatingStarElement>;
        }
    }
}
