
name: a11y test

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: update apt
      run: sudo apt update -y
    - name: Install wget
      run: sudo apt install wget
    - name: Download chrome installation file
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Install required packages
      run: sudo apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 libxshmfence1 xdg-utils
    - name: Install Chrome
      run: sudo dpkg -i google-chrome-stable_current_amd64.deb
    - name: Install dependencies for chromedriver
      run: sudo apt-get install -y libxss1 libappindicator1 libindicator7 xvfb unzip
    - name: Download chromedriver and make it executable
      run: wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
    - name: unzip
      run: unzip chromedriver_linux64.zip
    - name: make executable
      run: chmod +x chromedriver
    - name: Move executable and create symlinks
      run: sudo mv -f chromedriver /usr/local/share/chromedriver
    - name: create symlink1
      run: sudo ln -fs /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - name: create symlink2
      run: sudo ln -fs /usr/local/share/chromedriver /usr/bin/chromedriver

